import type { Category } from '@/types'

export interface HouseholdItem {
  name: string
  category: Category
  unit: string
}

export const PRESET_ITEMS: HouseholdItem[] = [
  // Food & Beverages
  { name: 'Whole Milk', category: 'Food & Beverages', unit: 'liters' },
  { name: 'Skim Milk', category: 'Food & Beverages', unit: 'liters' },
  { name: 'Eggs', category: 'Food & Beverages', unit: 'pieces' },
  { name: 'Butter', category: 'Food & Beverages', unit: 'pieces' },
  { name: 'Cheese', category: 'Food & Beverages', unit: 'pieces' },
  { name: 'Yogurt', category: 'Food & Beverages', unit: 'pieces' },
  { name: 'Bread', category: 'Food & Beverages', unit: 'pieces' },
  { name: 'White Rice', category: 'Food & Beverages', unit: 'kg' },
  { name: 'Brown Rice', category: 'Food & Beverages', unit: 'kg' },
  { name: 'Pasta', category: 'Food & Beverages', unit: 'packs' },
  { name: 'Flour', category: 'Food & Beverages', unit: 'kg' },
  { name: 'Sugar', category: 'Food & Beverages', unit: 'kg' },
  { name: 'Salt', category: 'Food & Beverages', unit: 'pieces' },
  { name: 'Cooking Oil', category: 'Food & Beverages', unit: 'liters' },
  { name: 'Olive Oil', category: 'Food & Beverages', unit: 'bottles' },
  { name: 'Vinegar', category: 'Food & Beverages', unit: 'bottles' },
  { name: 'Soy Sauce', category: 'Food & Beverages', unit: 'bottles' },
  { name: 'Ketchup', category: 'Food & Beverages', unit: 'bottles' },
  { name: 'Mayonnaise', category: 'Food & Beverages', unit: 'pieces' },
  { name: 'Coffee', category: 'Food & Beverages', unit: 'packs' },
  { name: 'Tea Bags', category: 'Food & Beverages', unit: 'boxes' },
  { name: 'Orange Juice', category: 'Food & Beverages', unit: 'liters' },
  { name: 'Mineral Water', category: 'Food & Beverages', unit: 'bottles' },
  { name: 'Canned Tuna', category: 'Food & Beverages', unit: 'cans' },
  { name: 'Canned Beans', category: 'Food & Beverages', unit: 'cans' },
  { name: 'Canned Tomatoes', category: 'Food & Beverages', unit: 'cans' },
  { name: 'Oats', category: 'Food & Beverages', unit: 'packs' },
  { name: 'Cereal', category: 'Food & Beverages', unit: 'boxes' },
  { name: 'Honey', category: 'Food & Beverages', unit: 'bottles' },
  { name: 'Peanut Butter', category: 'Food & Beverages', unit: 'pieces' },
  { name: 'Jam', category: 'Food & Beverages', unit: 'pieces' },
  { name: 'Chicken', category: 'Food & Beverages', unit: 'kg' },
  { name: 'Ground Beef', category: 'Food & Beverages', unit: 'kg' },
  { name: 'Potatoes', category: 'Food & Beverages', unit: 'kg' },
  { name: 'Onions', category: 'Food & Beverages', unit: 'kg' },
  { name: 'Garlic', category: 'Food & Beverages', unit: 'pieces' },
  { name: 'Tomatoes', category: 'Food & Beverages', unit: 'kg' },
  { name: 'Carrots', category: 'Food & Beverages', unit: 'kg' },
  { name: 'Apples', category: 'Food & Beverages', unit: 'kg' },
  { name: 'Bananas', category: 'Food & Beverages', unit: 'pieces' },
  { name: 'Lemons', category: 'Food & Beverages', unit: 'pieces' },
  { name: 'Cream', category: 'Food & Beverages', unit: 'ml' },
  { name: 'Baking Soda', category: 'Food & Beverages', unit: 'pieces' },
  { name: 'Baking Powder', category: 'Food & Beverages', unit: 'pieces' },
  { name: 'Black Pepper', category: 'Food & Beverages', unit: 'pieces' },
  { name: 'Chicken Broth', category: 'Food & Beverages', unit: 'liters' },
  { name: 'Evaporated Milk', category: 'Food & Beverages', unit: 'cans' },
  { name: 'Condensed Milk', category: 'Food & Beverages', unit: 'cans' },

  // Cleaning Supplies
  { name: 'Dishwashing Liquid', category: 'Cleaning Supplies', unit: 'bottles' },
  { name: 'Dishwasher Pods', category: 'Cleaning Supplies', unit: 'pieces' },
  { name: 'Laundry Detergent', category: 'Cleaning Supplies', unit: 'kg' },
  { name: 'Bleach', category: 'Cleaning Supplies', unit: 'liters' },
  { name: 'Multi-Surface Cleaner', category: 'Cleaning Supplies', unit: 'bottles' },
  { name: 'Toilet Bowl Cleaner', category: 'Cleaning Supplies', unit: 'bottles' },
  { name: 'Glass Cleaner', category: 'Cleaning Supplies', unit: 'bottles' },
  { name: 'Floor Cleaner', category: 'Cleaning Supplies', unit: 'liters' },
  { name: 'Bathroom Cleaner', category: 'Cleaning Supplies', unit: 'bottles' },
  { name: 'Disinfectant Spray', category: 'Cleaning Supplies', unit: 'bottles' },
  { name: 'Sponges', category: 'Cleaning Supplies', unit: 'pieces' },
  { name: 'Scrub Brush', category: 'Cleaning Supplies', unit: 'pieces' },
  { name: 'Trash Bags', category: 'Cleaning Supplies', unit: 'rolls' },
  { name: 'Mop Refill', category: 'Cleaning Supplies', unit: 'pieces' },
  { name: 'Broom', category: 'Cleaning Supplies', unit: 'pieces' },
  { name: 'Microfiber Cloths', category: 'Cleaning Supplies', unit: 'pieces' },
  { name: 'Rubber Gloves', category: 'Cleaning Supplies', unit: 'pieces' },
  { name: 'Air Freshener', category: 'Cleaning Supplies', unit: 'pieces' },
  { name: 'Drain Unclogger', category: 'Cleaning Supplies', unit: 'bottles' },
  { name: 'Fabric Softener', category: 'Laundry', unit: 'liters' },

  // Personal Care
  { name: 'Shampoo', category: 'Personal Care', unit: 'bottles' },
  { name: 'Conditioner', category: 'Personal Care', unit: 'bottles' },
  { name: 'Body Wash', category: 'Personal Care', unit: 'bottles' },
  { name: 'Bar Soap', category: 'Personal Care', unit: 'pieces' },
  { name: 'Hand Soap', category: 'Personal Care', unit: 'bottles' },
  { name: 'Toothpaste', category: 'Personal Care', unit: 'pieces' },
  { name: 'Toothbrush', category: 'Personal Care', unit: 'pieces' },
  { name: 'Dental Floss', category: 'Personal Care', unit: 'pieces' },
  { name: 'Mouthwash', category: 'Personal Care', unit: 'bottles' },
  { name: 'Deodorant', category: 'Personal Care', unit: 'pieces' },
  { name: 'Face Wash', category: 'Personal Care', unit: 'bottles' },
  { name: 'Moisturizer', category: 'Personal Care', unit: 'pieces' },
  { name: 'Sunscreen', category: 'Personal Care', unit: 'pieces' },
  { name: 'Razors', category: 'Personal Care', unit: 'pieces' },
  { name: 'Shaving Cream', category: 'Personal Care', unit: 'pieces' },
  { name: 'Cotton Balls', category: 'Personal Care', unit: 'bags' },
  { name: 'Cotton Buds', category: 'Personal Care', unit: 'boxes' },
  { name: 'Feminine Wash', category: 'Personal Care', unit: 'bottles' },
  { name: 'Sanitary Pads', category: 'Personal Care', unit: 'packs' },
  { name: 'Tissue Paper', category: 'Personal Care', unit: 'rolls' },
  { name: 'Facial Tissue', category: 'Personal Care', unit: 'boxes' },
  { name: 'Wet Wipes', category: 'Personal Care', unit: 'packs' },
  { name: 'Hand Sanitizer', category: 'Personal Care', unit: 'bottles' },
  { name: 'Bandages', category: 'Personal Care', unit: 'boxes' },
  { name: 'Rubbing Alcohol', category: 'Personal Care', unit: 'bottles' },

  // Kitchen
  { name: 'Aluminum Foil', category: 'Kitchen', unit: 'rolls' },
  { name: 'Plastic Wrap', category: 'Kitchen', unit: 'rolls' },
  { name: 'Parchment Paper', category: 'Kitchen', unit: 'rolls' },
  { name: 'Paper Towels', category: 'Kitchen', unit: 'rolls' },
  { name: 'Zip-Lock Bags', category: 'Kitchen', unit: 'boxes' },
  { name: 'Disposable Cups', category: 'Kitchen', unit: 'packs' },
  { name: 'Disposable Plates', category: 'Kitchen', unit: 'packs' },
  { name: 'Disposable Utensils', category: 'Kitchen', unit: 'packs' },
  { name: 'Matchsticks', category: 'Kitchen', unit: 'boxes' },
  { name: 'Lighter', category: 'Kitchen', unit: 'pieces' },
  { name: 'Cooking Gas', category: 'Kitchen', unit: 'pieces' },

  // Laundry
  { name: 'Laundry Pods', category: 'Laundry', unit: 'pieces' },
  { name: 'Stain Remover', category: 'Laundry', unit: 'bottles' },
  { name: 'Dryer Sheets', category: 'Laundry', unit: 'boxes' },
  { name: 'Clothespins', category: 'Laundry', unit: 'pieces' },
  { name: 'Ironing Board Cover', category: 'Laundry', unit: 'pieces' },
  { name: 'Laundry Basket', category: 'Laundry', unit: 'pieces' },
]
